name: unsplash_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: 5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: 2.6.1
  freezed_annotation: 2.4.4
  riverpod_annotation: 2.6.1
  talker_dio_logger: 4.5.1
  talker_flutter: 4.5.1
  talker_riverpod_logger: 4.5.1

dev_dependencies:
  build_runner: 2.4.13
  custom_lint: 0.7.0
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  json_serializable: 6.9.0
  retrofit: 4.4.1
  retrofit_generator: 9.1.5
  riverpod_generator: 2.6.3
  riverpod_lint: 2.6.3

flutter:
  uses-material-design: true
